<?php

namespace AppBundle\Repository;

/**
 * Dis_SympRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dis_SympRepository extends \Doctrine\ORM\EntityRepository
{
}
