<?php

namespace AppBundle\Repository;

/**
 * DiseaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiseaseRepository extends \Doctrine\ORM\EntityRepository
{
}
