<?php

namespace AppBundle\Repository;

/**
 * Doc_HosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Doc_HosRepository extends \Doctrine\ORM\EntityRepository
{
}
