<?php

namespace AppBundle\Repository;

/**
 * Doc_DisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Doc_DisRepository extends \Doctrine\ORM\EntityRepository
{
}
