<?php

namespace AppBundle\Repository;

/**
 * MedicalRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
