<?php

namespace AppBundle\Repository;

/**
 * pre_reqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pre_reqRepository extends \Doctrine\ORM\EntityRepository
{
}
