<?php

namespace AppBundle\Repository;

/**
 * SymptomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymptomRepository extends \Doctrine\ORM\EntityRepository
{
}
